name: Generate Snake Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # ✅ This is the key fix

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: soheltanvir0699
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate contribution snake"
          add: "dist/*.svg"
